#!/bin/bash

isp_connection_start(){
  if which ifup > /dev/null; then
    ifup $INTERFACE
  else
    netctl start $INTERFACE
  fi
}

isp_connection_status(){
  if [ "$( isp_connected)" = "yes" ]; then
    echo "3"
  else
    echo "1"
  fi
}

isp_connection_stop(){
  if which ifdown > /dev/null; then
    ifup $INTERFACE
  else
    netctl stop $INTERFACE
  fi
}

isp_may_disconnect(){
  loga Not disconnecting
}

isp_connected(){
  if ifconfig | grep -q $INTERFACE; then
    echo yes
  else
    echo no
  fi
}
