#!/bin/bash

# Some simple methods to interact with a USB-2G or 3G key

get_ussd(){
  log USSD-call "*$1#"
  gsm-ussd -m $DEV --no-cleartext "*$1#" 2>/dev/null
}

ussd_encode(){
  perl -e "@a=split(//,unpack('b*',\"*$1#\")); for (\$i=7; \$i < \$#a; \$i+=8) { \$a[\$i]='' } print uc(unpack('H*', pack('b*', join('', @a))))"
}

ussd_decode(){
  perl -e "@a=split(//,unpack('b*', pack('H*',\"$1\"))); for (\$i=6; \$i < \$#a; \$i+=7) {\$a[\$i].='0' } print pack('b*', join('', @a))"
}

gcom_call(){
  comgt -s -d $DEV $WDIR/gcom/$1.gcom | sed -e 's/",15//'
}

rs(){
  echo "$1" | grep -qi "$2"
}

sms_delete(){
  if [ -e $DEV ]; then
    # Start with an empty SMS
    gnokii --deletesms SM 0 29 > /dev/null 2>&1
  fi
}

grep_pppd(){
  if [ -f /var/log/syslog ]; then
    grep -a pppd /var/log/syslog | tail | grep -A 10 started
  else
    journalctl -b /usr/bin/pppd | grep -a pppd | tail -n 20 | grep -A 20 ": pppd.*started"
  fi
}

