#!/bin/bash

# This is a network-library that does
# - lib_captive: create and administer a captive portal
# - lib_isp: interact with ISPs - we want to have
#   - lib_isp_tigo: Tigo USB-key
#   - lib_isp_prestabist: Prestabist modem
#   - lib_isp_tawali: Tawali USB-key
#   - lib_isp_airtel: Airtel USB-key
# - lib_misc: small hacks like mail-queue and synching

# Don't need to change anything below this lines...
WDIR=$( dirname ${BASH_SOURCE[0]} )
RUN=/var/run/lib-net
LOG=/var/log/lib-net
DATE=$( date +%y%m%d-%H.%M )
PATH=$PATH:/sbin:/usr/sbin
if [ -x /etc/multiconf/conf.d/captive ]; then
  . /etc/multiconf/conf.d/captive
else
  if pwd | egrep -q "/Test$"; then
    . $WDIR/multiconf-captive
    RUN=$WDIR/run
    LOG=$WDIR/log
    iptables(){
      log Iptables $@
    }
    ip(){
      log ip $@
    }
  else
    if [ ! -x $WDIR/multiconf-captive ]; then
      cp $WDIR/multiconf-captive.orig $WDIR/multiconf-captive
    fi
    . $WDIR/multiconf-captive
  fi
fi

if [ "$ISP" = "simul" ]; then
  LOG=$WDIR/log
  RUN=$WDIR/run
  iptables(){
    log Iptables $@
  }
  ip(){
    log ip $@
  }
fi
CONNSTAT=$RUN/connection
MSGS=$LOG/msgs.log
ACTIONLOG=$LOG/action.log

mkdir -p $RUN $LOG
if [ "$ISP" != "simul" -a "$ISP" != "test" ]; then
  sudo chown -R www-data.www-data $RUN $LOG
fi

#
# Different kind of logging facilities
#

msg() {
  WHO=$1
  shift
  echo $( date +%F_%R ) - $WHO: $@ >> $MSGS
}

log(){
  msg simple "$@"
#  logger -- $@
}

logf(){
  msg function "$@"
#  logger -- $@
}

loga(){
  msg action $@
  echo $DATE $@ >> $ACTIONLOG
}

#
# Loading of other libraries
#

for lib in misc users captive isp; do
  . $WDIR/lib_$lib
done

#
# Let's call an eventual function and print some variables
#

if [ "$1" ]; then
  VAR=""
  if [ $1 = print ]; then
    shift
    VAR=$1
    shift
  fi
  if [ "$1" = func ]; then
    shift
    FUNC=$1
    shift
    $FUNC $@
  fi
  if [ "$VAR" ]; then
    # There must be a better way to do that...
    set | grep "^$VAR=" | sed -e "s/.*=//"
  fi
fi
