#!/bin/sh

if [ "$LIB_TEST" = "loaded" ]; then
  return
echo
fi
LIB_TEST=loaded
CONN_STATUS=$RUN/connection_status

#
# Connection-start, status, stop
#

isp_connection_start(){
  actionlog Starting connection
  echo 4 > $CONN_STATUS
}

isp_connection_status(){
  echo $CONN_STATUS
}

isp_connection_stop(){
  actionlog Stopping connection
  echo 0 > $CONN_STATUS
}

isp_connected(){
  if grep -q 4 $CONN_STATUS; then
    echo yes
  else
    echo no
  fi
}
