#!/bin/bash

isp_restart(){
  if [ "$CONN_TYPE" = "always_on" ]; then
    isp_connection_stop
    isp_connection_start
    if [ -f $USERS_CONNECTED ]; then
      rm -f $USERS_CONNECTED
    fi
    captive_clear
  fi
}

isp_connect(){
  log Starting connection
  isp_connection_start
}

isp_may_disconnect(){
  isp_connection_stop
}

isp_disconnect(){
  log Stopping connection
  isp_connection_stop
}

isp_params(){
  echo "{\"isp\":\"$ISP\",\"conn_type\":\"$CONNECTION_TYPE\"," \
    "\"has_promo\":\"$HAS_PROMO\",\"has_credit\":\"$HAS_CREDIT\"}"
}

# Sets up and uses an ISP
test "$ISP" && . $WDIR/lib_isp_$ISP
