#!/bin/bash

# Here come small hacks to do on the internet
# - mail-sending over rsync
# - rsyncing a directory for basic dropbox-simulation
# - updating files

mail_get_queue(){
  postqueue -p | grep -v "Connection refused" -
}

mail_start_copy(){
  $WDIR/start_copy_emails
  rm /var/spool/postfix/hold/*
}

get_line_field(){
  grep $2 $1 | sed -e "s/ \+/ /g" | cut -d " " -f $3
}

uap_rx(){
  BYTES=$( get_line_field /proc/net/dev uap0 3 )
  echo ${BYTES:-0}
}

uap_tx(){
  BYTES=$( get_line_field /proc/net/dev uap0 11 )
  echo ${BYTES:-0}
}

ppp_rx(){
  BYTES=$( get_line_field /proc/net/dev ppp0 3 )
  echo ${BYTES:-0}
}

ppp_tx(){
  BYTES=$( get_line_field /proc/net/dev ppp0 11 )
  echo ${BYTES:-0}
}

remove_line(){
  SEARCH=$1
  FILE=$2

  egrep -v "$SEARCH" "$FILE" > "$FILE.tmp"
  mv "$FILE.tmp" "$FILE"
}

change_var(){
  local FILE=$1
  local VAR=$2
  local VALUE=$3
  loga "Going to change $VAR = -$VALUE- in $FILE"

  if egrep -q "^#*$VAR" $FILE; then
    perl -pi -e "s/^#*($VAR)=.*/\1=\"$VALUE\"/" $FILE
  else
    echo "$VAR=$VALUE" >> $FILE
  fi
  . $FILE
  loga $( set | egrep "^$VAR" )
}

set_multiconf(){
  local kv
  local k
  local v
  for kv in $@; do
    k=$( echo $kv | cut -f 1 -d "=" )
    v=$( echo $kv | cut -f 2 -d "=" )
    change_var $WDIR/multiconf-captive $k $v
  done
}

to_json(){
  RESULT=""
  
}

email_backup(){
  EMAIL=${1:-info@profeda.org}
  BACKUP="/tmp/backup-$DATE.tgz"
  tar czf $BACKUP /var/www/Gestion/data
  echo "Backup of Gestion from Bitkine" | 
    mail -a $BACKUP -s "Backup from Bitkine at $DATE" $EMAIL
}
