#!/bin/bash

isp_connection_start(){
  ifup wan
}

isp_connection_status(){
  if ! grep -q ppp0 /proc/net/dev; then
    echo "0"
  elif ! grep -q tun0 /proc/net/dev; then
    echo "3"
  else
    echo "4"
  fi
}

isp_connection_stop(){
  ifdown wan
}

isp_restart_wwan(){ 
  /etc/init.d/firewall restart 
  killall -9 wwan 
  sort /etc/captive/aon_connected | uniq > /tmp/ac 
  mv /tmp/ac /etc/captive/aon_connected 
  /etc/init.d/wwan restart 
} 
 
if [ "$FUNC" ]; then 
  $FUNC $@ 
fi 
 
isp_check_double_wwan(){ 
  WWANS=$( ps ax | grep /usr/bin/wwan | wc -l ) 
  if [ $WWANS -gt 2 ]; then 
    loga Restarting wwan because it has $WWANS... 
    ps ax 
    isp_restart_wwan 
  fi 
}     

isp_may_disconnect(){
  loga Not disconnecting
}

isp_connected(){
  if ifconfig | grep -q ppp0; then
    echo yes
  else
    echo no
  fi
}
