#!/bin/sh

if [ "$LIB_TIGO" = "loaded" ]; then
#  return
echo
fi
LIB_TIGO=loaded
. $WDIR/lib_usb

TIGO=$WDIR
CLEFT=$RUN/tigo_credit
PLEFT=$RUN/tigo_promotion
UDAILY=$LOG/usage_daily
UDAILY_TMP=$UDAILY.tmp
DEV=/dev/ttyUSB2
TIGO_STATUS=$RUN/tigo_status
touch $TIGO_STATUS 
for f in $CLEFT $PLEFT $UDAILY $UDAILY_TMP; do
  if [ ! -f $f ]; then
    log Setting $f to 0
    echo 0 > $f
  fi
done

#
# Promotion-add, get, update
#

isp_tigo_promotion_add(){
  log Promotion add $1 from user $2
  if [ "$1" ]; then
    case "$1" in
      hour|30MB)
        PROMOTION=1111
        COST=800
        ;;
      day|100MB)
        PROMOTION=2424
        COST=2500
        ;;
      week|1GB)
        PROMOTION=7777
        COST=15000
        ;;
      month|5GB)
        PROMOTION=3030
        COST=50000
        ;;
    esac
    log Sending promotion of $PROMOTION to Tigo
    if [ "$PROMOTION" ]; then
      # Testing for new version which has a global config-file
      if [ -f /etc/gammu.conf ]; then
        log Adding with gammu v2
        gammu sendsms TEXT $PROMOTION -text "kattir" 2>/dev/null
      else
        log Adding with gammu v1
        echo kattir | gammu --config $WDIR/conf/gammurc sendsms TEXT $PROMOTION 2>/dev/null
      fi
    fi
  fi
  isp_tigo_promotion_update
  isp_tigo_credit_update
  if [ "$PROMOTION_LEFT" -gt 20000000 ]; then
    log Promotion successful: user:$2 added promotion:$1 now promotion_left:$PROMOTION_LEFT and cost:$COST
  fi
}

isp_tigo_promotion_list(){
  grep "Promotion successful" $MSGS
}

isp_tigo_promotion_get_raw(){
  # This should also work.. - simple test-cases
  #STR="30.000 MB INTERNET valide avant 04/10/2012."
  #STR=" 30.000 MB INTERNET valide avant 04/10/2012."
  #STR="250.00 CFA recharge bonus, 30.000 MB INTERNET valide avant 04/10/2012."
  #STR="250.00 CFA recharge bonus."
  STR=$( ussd_decode $( gcom_call get_promotion ) )
  log "Got string $STR"
  if rs "$STR" Octet; then
    log Found octets
    echo $STR | sed -e "s/.*MMS, \(.*\) Octet.*/\1/"
  elif rs "$STR" "INTERNET"; then
    log Found INTERNET
    STR=$( echo $STR | sed -e "s/.*recharge bonus, //" )
    BYTES=$( echo $STR | sed -e "s/[^0-9]*\([0-9]*\.[0-9]* ..\) INTERNET.*/\1/" )
    logger $BYTES left on internet
    echo $BYTES
  elif rs "$STR" "a marche"; then
    log Waiting for SMS
    if [ -e $DEV ]; then
      for w in $( seq 10 ); do
        log Waiting till $(( w * 5 )) seconds
        BYTES=$( gnokii --getsms SM 0 29 -d 2>&1 | grep octet | tail -n 1 )
        if [ "$BYTES" ]; then
          break;
        fi
        sleep 5
      done
    fi
    #sms_delete
    echo $BYTES | sed -e "s/.*MMS, \(.*\) octet.*/\1/"
  elif rs "$STR" "Vous n'avez pas"; then
    log "No promotion"
    echo 0
  elif rs "$STR" "recharge bonus"; then
    log "No promotion"
    echo 0
  elif rs "$STR" "KATTIR"; then
    log "Lonely kattir-message"
    echo 0
  fi
}

isp_tigo_promotion_get(){
  STR=$( isp_tigo_promotion_get_raw )
  if rs "$STR" MB; then
    echo "scale=0; ${STR/ MB/} * 1000000 / 1" | bc
  elif rs "$STR" kB; then
    echo "scale=0; ${STR/ kB/} * 1000 / 1" | bc
  else
    echo "$STR"
  fi
}

isp_tigo_promotion_update(){
  log Getting promotion
  P=$( isp_tigo_promotion_get )
  if [ "$P" ]; then
    echo $P > $PLEFT
  fi
  isp_update_vars
}

#
# Credit-add, send, get, update
#

isp_tigo_credit_add(){
  STR=$( get_ussd "123*$1" )
  log "Added credit $STR"
  isp_tigo_credit_update
  echo $STR
}

isp_tigo_credit_send(){
  STR=$( get_ussd "190*1234*235$2*$1" )
  log "Sent credit $2 to $1 -> $STR"
  isp_tigo_credit_update
  echo $STR
}

isp_tigo_credit_get(){
  STR=$( ussd_decode $( gcom_call get_credit ) )
  log "Got credit $STR"
  if rs "$STR" solde; then
    echo $STR | sed -e "s/.*est de \([0-9]*\)\..*/\1/"
  fi
}

isp_tigo_get_cell(){
  STR=$( gcom_call get_cell )
  log "Got cell $STR"
  echo $STR
}

isp_tigo_get_signal(){
  STR=$( gcom_call get_signal )
  log "Got signal $STR"
  echo $STR
}

isp_tigo_credit_update(){
  log Getting credit
  C=$( isp_tigo_credit_get )
  if [ "$C" ]; then
    echo $C | sed -e "s/\..*//" > $CLEFT
  fi
}

#
# Connection-start, status, stop
#

isp_connection_start(){
  if [ "$( isp_connection_status )" -gt 3 ]; then
    loga Connection already up
    return
  fi
  if ! grep -q starting $TIGO_STATUS; then
    loga Starting tigo-connection
    pon tigo
    sleep 4
    if ! ps ax | grep -q pppd; then
      loga Oups - restarting connection
      while poff -a; do
        log Killing pppd
      done 
      pon tigo
    fi
    echo $( date +%s ) - start > $CONNSTAT
    echo starting > $TIGO_STATUS
    iptables -t nat -I POSTROUTING -o ppp0 -j MASQUERADE
  fi
}

isp_connection_status(){
  if grep_pppd | grep -q failed; then
    isp_connection_stop
    isp_connection_start
    echo 0
    return
  fi
  PPP=$( ip link | grep " ppp" | sed -e "s/.*\(ppp.\).*/\1/" )
  PAP=$( grep_pppd | grep PAP )
  PPP_IP=$( grep_pppd grep -A 3 PAP | grep local | sed -e "s/.* //" )
  TUN=$( ip link | grep " tun" | sed -e "s/.*\(tun.\).*/\1/" )
  ret=0
  for a in "$PPP" "$PAP" "$PPP_IP" "$TUN" ""; do
    if [ "$a" ]; then
      ret=$(( ret + 1 ))
    else
      echo $ret
      return
    fi
  done
}

isp_connection_stop(){
  if [ "$CONNECTION_TYPE" = "permanent" ]; then
    loga Not closing connection
    return
  fi
  if ! grep -q stopping $TIGO_STATUS; then
    echo stopping > $TIGO_STATUS
    echo $( date +%s ) - stop > $CONNSTAT
    loga Stopping tigo-connection
    while poff -a; do sleep 2; done
    iptables -t nat -D POSTROUTING -o ppp0 -j MASQUERADE
  fi
  isp_tigo_promotion_update
}

isp_connected(){
  if ifconfig | grep -q ppp; then
    echo yes
  else
    echo no
  fi
}

isp_reset_usage_connection(){
  echo 0 > $UDAILY_TMP
}

isp_reset_usage_daily(){
  TDAY=$( date +%D )
  if ! grep -q $TDAY $LOG/usage_reset_last; then
    echo $TDAY > $LOG/usage_reset_last
    echo 0 > $UDAILY
  fi
}

isp_update_daily(){
  USAGE_NOW=$(( $( ppp_rx ) + $( ppp_tx ) ))
  if [ "$USAGE_NOW" -gt 0 ]; then
    USAGE_DIFF=$(( USAGE_NOW - $( cat $UDAILY_TMP ) ))
    echo $USAGE_NOW > $UDAILY_TMP
    USAGE_DAILY=$(( $( cat $UDAILY ) + $USAGE_DIFF ))
    log Usage_now_diff_daily are $USAGE_NOW - $USAGE_DIFF - $USAGE_DAILY
    if [ "$USAGE_DAILY" ]; then
      echo $USAGE_DAILY > $UDAILY
    else
      echo 0 > $UDAILY
    fi
  else
    echo 0 > $UDAILY_TMP
  fi
}

isp_setup(){
  isp_reset_usage_daily
}

isp_update_vars(){
  if [ ! "$CLEFT$PLEFT" ]; then
    return
  fi
  if [ ! -f $CLEFT ]; then
    isp_tigo_credit_update
  fi
  CREDIT_LEFT=$( cat $CLEFT )
  if [ ! -f $PLEFT ]; then
    isp_tigo_promotion_update
  fi
  PROMOTION_LEFT=$(( $( cat $PLEFT ) - $( ppp_rx ) - $( ppp_tx ) ))
  isp_update_daily
  USAGE_DAILY=$( cat $UDAILY )
}

isp_update_vars
