#!/bin/bash

# Connection-type - permanent or ondemand
CONNECTION_TYPE=permanent
INTERFACE=eth2

# Cost per minute
# Base cost
COST_BASE=5
# Cost shared between users
COST_SHARED=10

HAS_PROMO=false

HAS_CREDIT=false

ALLOW_FREE=true
