#!/bin/bash

# Connection-type - permanent or ondemand
CONNECTION_TYPE=ondemand

# Cost per minute
# Base cost
COST_BASE=5
# Cost shared between users
COST_SHARED=10

HAS_PROMO=true

HAS_CREDIT=true

ALLOW_FREE=false
