#!/bin/bash
cat - <<EOF | mail -s "From Bitkine" info@profeda.org 
Hello from Bitkine at

$( date )

System is

$( uptime ) - $( df -h )

Tigo-promotion is $( /var/www/LibNet/lib_net print PROMOTION_LEFT )
Tigo-credit is    $( /var/www/LibNet/lib_net print CREDIT_LEFT )

.
EOF
