#!/bin/bash
WDIR=$( dirname ${BASH_SOURCE[0]} )

echo Copying some sripts
ln -s $WDIR/bash_profile /root/.bash_profile
ln -s $WDIR/vimrc /root/.vimrc

echo Installing supplemental packages
pacman -S ppp rsync vim mercurial usb_modeswitch
pacman -S squid apache openvpn

echo configuring apache
mkdir /etc/http/conf/sites
ln -s $WDIR/999* /etc/http/conf/sites

echo Making squid-cache-dirs
squid -z
ln -s $WDIR/squid.conf /etc/squid

echo Adjusting usb_modeswitch
perl -pi -e "s/.SetStorageDelay.*/SetStorageDelay=3/" /etc/usb_modeswitch.conf

echo Enabling gestion, http and squid
for service in ../../Gestion/Binaries/gestion.service http squid; do
  systemctl enable service
  systemctl start service
done

