#!/bin/bash
WDIR=$( dirname ${BASH_SOURCE[0]} )
cd $WDIR
WDIR=$( pwd )
echo WDIR is $WDIR

echo Copying some sripts
rm /root/.bash_profile /root/.vimrc
ln -s $WDIR/bash_profile /root/.bash_profile
ln -s $WDIR/vimrc /root/.vimrc

echo Installing supplemental packages
pacman -S ppp rsync vim mercurial usb_modeswitch
pacman -S squid apache openvpn iftop tcpdump

echo -n "Install everything (Y/n)? "
read a
if [ $a != "n" -a $a = "N" ]; then
  pacman -S libreoffice-en-US libreoffice-base libreoffice-calc libreoffice-draw \
    libreoffice-sdk libreoffice-impress libreoffice-math libreoffice-writer \
    ttf-dejavu libxinerama yaourt
fi

echo configuring apache
mkdir -p /etc/httpd/conf/sites
rm /etc/httpd/conf/sites/999*
ln -s $WDIR/999* /etc/httpd/conf/sites

echo Making squid-cache-dirs
squid -z
rm /etc/squid/squid.conf
ln -s $WDIR/squid.conf /etc/squid

echo Adjusting usb_modeswitch
perl -pi -e "s/.SetStorageDelay.*/SetStorageDelay=3/" /etc/usb_modeswitch.conf

echo Enabling gestion, httpd and squid
cd ../../Gestion/Binaries
for service in $(pwd)/gestion.service httpd squid; do
  systemctl enable $service
  systemctl start $service
done

