alias vi='vim'
alias restart='systemctl restart'
alias start='systemctl start'
alias stop='systemctl stop'
alias status='systemctl status'

export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'
alias p=ping

export PATH=$PATH:~/bin
