#!/bin/bash
. ../../Config/lib_config

#dpkg -i $DIR/gsm-ussd_0.3.3-0_all.deb 
link libnet-reset /etc/ppp/ip-up.d
link ntpdate /etc/ppp/ip-up.d
link 8led /etc/ppp/ip-up.d
link tigo /etc/ppp/peers
inst "Enable proxy- and rewrite-module" "a2enmod proxy" "a2enmod proxy_http" "a2enmod rewrite"
for site in 999-gestion_internet; do
  link $site /etc/apache2/sites-enabled
done
/etc/init.d/apache2 restart

for f in check_ppp_crontab reset_usage_daily; do
  link $f /etc/cron.d
done

echo - "internet-stick is e303 or e100? "
read stick
$WDIR/gcom_config $stXrick
