#!/bin/sh

route add lev-vpn gw 10.64.64.64
service openvpn start
while ! ifconfig tun0 > /dev/null; do
  if ! ifconfig ppp0 > /dev/null; then
    return
  fi
done
VPN=$( ip addr show dev tun0 | grep peer | sed -e "s/.*peer \(.*\).32 scope.*/\1/" )
logger VPN is at address $VPN
route add default gw $VPN
