#!/bin/bash
WDIR=$( dirname ${BASH_SOURCE[0]} )
RUN=/var/run/lib-net/ppp_loop
echo > $RUN
ISP=${1:-provider}
HAS_PROMO=$( $WDIR/../lib_net print HAS_PROMO )

stop_ppp(){
  while poff -a; do
    sleep 1
  done
  sleep 1
}

while [ "$( cat $RUN )" != "stop" ]; do
  if [ "$HAS_PROMO" = "true" ]; then
    PL=$( $WDIR/../lib_net print PROMOTION_LEFT )
    if [ "$PL" ]; then
      if [ "$PL" -gt 500000 ]; then
        if ! pidof pppd; then
          stop_ppp
          pon $ISP
        fi
      else
        stop_ppp
        exit
      fi
    fi
  else
    if ! pidof pppd; then
      stop_ppp
      pon $ISP
    fi
  fi
  sleep 5
done
stop_ppp
