#!/bin/bash

BASE=/var/www/transfert
LOG=$BASE/files
HEADER=$BASE/head.html
WWW=$BASE/index.html
SRC=/media/bethanie/Transfert
#ARCHIVE=$SRC/Archive
DST=bethanie@profeda.org:Transfert
URL=profeda.org/Transfert/Bethanie
WAIT_RECONNECT=5

log(){
  echo "$( date ) - $@<br>" >> $LOG
  cat $HEADER > $WWW
  tac $LOG >> $WWW
}

connect(){
  log Opening connection
  /var/www/LibNet/lib_net func user_connect localhost transfert
}

disconnect(){
  /var/www/LibNet/lib_net func user_disconnect localhost transfert
  log Disconnected
}

if [ $( ls $SRC/ | wc -l ) = "0" ]; then
  exit
fi

connect
log Starting to copy files $( ls $SRC ) to $DST

rename "s/ /_/g" $SRC/*
for file in $SRC/*; do
  log Doing file $file
  chmod a+r $file
  while ! rsync -Paivz -e "ssh -p 502" $file $DST; do
    log Broken, trying again
    disconnect
    sleep $WAIT_RECONNECT
    connect
    sleep $WAIT_RECONNECT
  done
  URL="http://$URL/$( basename $file )"
  log "Done $file - Link is <a href='$URL'>$URL</a>"
  if [ "$ARCHIVE" ]; then
    mv $file $ARCHIVE
  else
    rm $file
  fi
done

log Done copying files
disconnect

