#!/bin/bash
AVAST_DIR=/media/bethanie/Logiciels
logger -t update_antivirus Starting download of avast
cd $AVAST_DIR

if [ "$( pwd )" != $AVAST_DIR ]; then
  logger -t update_antivirus Couldnt change to directory, aborting
  exit
fi

/var/www/LibNet/lib_net func user_connect localhost local
sleep 5
logger -t update_antivirus Waiting for connection
while ! ifconfig | grep -q ppp0; do
  logger -t update_antivirus Connection not OK, resetting
  /var/www/LibNet/lib_net func user_disconnect localhost local
  /var/www/LibNet/lib_net func user_connect localhost local
  sleep 5
done

logger -t update_antivirus Connection OK, downloading
for a in avast avast-update; do
  logger -t update_antivirus Getting $a
  rm $a.file
  wget http://profeda.org/Files/$a.file
  echo rsync -Paiv -e "ssh -p 502" bethanie@profeda.org:Files/$( basename $( head -n 1 $a.file ) ) .
done

if [ -x ./update_files ]; then
  logger -t update_antivirus Updating files
  ./update_files do_dokuwiki
fi

logger -t update_antivirus Disconnecting
/var/www/LibNet/lib_net func user_disconnect localhost local
